/**
 * JournalEntryForm component - implements logic that handles any the submission of any component added to the page generated by JournalEntryFormHTML component. 
 */

import { JournalEntryFormHTML } from './JournalEntryFormHTML.js';
import { JournalEntryFormError } from './JournalEntryFormError.js';
import { getMoodEmoji } from '../utilities/moodEmojis.js';
import { validator } from './JournalEntryFormValidator.js';
import { saveJournalEntry, updateJournalEntry } from '../JournalEntry/JournalDataProvider.js';

const eventHub = document.querySelector('.container');

/**
 * Render a Journal Entry Form directly to the DOM node with class .entry-form-container
 */
export const JournalEntryForm = () => {
  document
    .querySelector('.entry-form-container')
    .innerHTML = JournalEntryFormHTML();
};

/**
 * Get the selector to use for using document.querySelector to obtain a reference to the <form> DOM node that is being interacted with.
 * @param {String} id The id number of the entry that this form is editing, if applicable.
 */
const getFormSelector = id => {
  let formSelector = '#entry-form';
  if(id) formSelector += `--${id}`;
  return formSelector;
};

/**
 * Factory function to create a journalEntry object from the current data in the form.
 * @param {String} id The id number of the entry that this form is editing, if applicable.
 */
const createJournalEntryObjectFromFormData = (id) => {
  const journalEntry = {};

  const { elements } = document.querySelector(getFormSelector(id));
  for(const element of elements) {
    if(element.nodeName.toLowerCase() !== 'button' && element.nodeName.toLowerCase() !== 'fieldset') {
      journalEntry[element.name] = element.value;
    }
  }

  return journalEntry;
};

/**
 * Clear out all error messages from the DOM
 * @param {String} id The id number of the entry that this form is editing, if applicable.
 */
const clearErrorMessages = id => {
  document
    .querySelectorAll(`${getFormSelector(id)} .entry-form__errors`)
    .forEach(errorMessageNode => errorMessageNode.innerHTML = '');
};

/**
 * Render validation errors to the DOM.
 * @param {Array} errors Array of error objects from the Validator.
 * @param {String} id The id number of the entry that this form is editing, if applicable.
 */
const renderErrors = (errors, id) => {
  clearErrorMessages(id);

  errors.forEach(error => {
    const errorMessageNode = document.querySelector(`${getFormSelector(id)} .entry-form__${error.propertyName}-errors`);
    errorMessageNode.innerHTML += JournalEntryFormError(error.errorMessage);
  });
};

/**
 * Set the disabled attribute for each input in the form to true.
 * @param {String} id The id number of the entry that this form is editing, if applicable.
 */
const disableForm = id => {
  for(const element of document.querySelector(getFormSelector(id)).elements) {
    element.disabled = true;
  }
};

/**
 * Event listener to update mood emoji rendered in form for mood input element.
 */
eventHub.addEventListener('input', event => {
  if(event.target.className === 'entry-form__mood') {
    const id = event.target.id.split('--')[1];
    const moodEmojiContentTarget = document.querySelector(`#entry-form__mood-emoji${id ? `--${id}` : ''}`);
    moodEmojiContentTarget.innerHTML = getMoodEmoji(event.target.value);
  }
});

/**
 * Event listener for form submit. Will either save a new journal entry object, or update an existing edited journal entry object.
 * Only saves if the journalEntry object passes all validation tests, renders errors to DOM if errors detected in object.
 */
eventHub.addEventListener('submit', event => {
  const [ nodeId, entryId ] = event.target.getAttribute('id').split('--');

  if(nodeId === 'entry-form') {
    event.preventDefault();

    const journalEntry = createJournalEntryObjectFromFormData(entryId);

    const errors = validator.validate(journalEntry);
    renderErrors(errors, entryId);

    if(errors.length === 0) {
      disableForm(entryId);

      if(entryId) {
        updateJournalEntry(journalEntry);
      }
      else {
        saveJournalEntry(journalEntry);
      }
    }
  }
});

/**
 * Event listener to re-render empty and enabled form after successful entry save.
 */
eventHub.addEventListener('journalEntriesStateChanged', JournalEntryForm);